"""campo_description_users_nullable

Revision ID: 00128058d6c2
Revises: 3ce003650cb3
Create Date: 2025-10-18 22:40:42.670895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00128058d6c2'
down_revision: Union[str, Sequence[str], None] = '3ce003650cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'description',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
