"""Adicionar_Tabela_Lancamentos

Revision ID: 2fbe68ce301b
Revises: 43afb92b02bb
Create Date: 2025-09-21 10:50:12.671741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2fbe68ce301b'
down_revision: Union[str, Sequence[str], None] = '43afb92b02bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('entry_types',
  sa.Column('id', sa.Integer(), nullable=False),
  sa.Column('name', sa.String(length=50), nullable=False),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_entry_types_id'), 'entry_types', ['id'], unique=False)
  op.create_index(op.f('ix_entry_types_name'), 'entry_types', ['name'], unique=True)
  op.execute(sa.text("INSERT INTO entry_types (id, name) VALUES (1, 'Receita'), (2, 'Despesa');"))

  op.create_table('entries',
  sa.Column('id', sa.Integer(), nullable=False),
  sa.Column('title', sa.String(length=100), nullable=False),
  sa.Column('entry_date', sa.String(length=10), nullable=False),
  sa.Column('description', sa.String(length=500), nullable=False),
  sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
  sa.Column('entry_type_id', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['entry_type_id'], ['entry_types.id'], ),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_entries_entry_date'), 'entries', ['entry_date'], unique=False)
  op.create_index(op.f('ix_entries_entry_type_id'), 'entries', ['entry_type_id'], unique=False)
  op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
  op.drop_index(op.f('ix_entry_type_id'), table_name='entry_type')
  op.drop_index(op.f('ix_entry_type_name'), table_name='entry_type')
  op.drop_table('entry_type')
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('entry_type',
  sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
  sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
  sa.PrimaryKeyConstraint('id'),
  mysql_collate='utf8mb4_0900_ai_ci',
  mysql_default_charset='utf8mb4',
  mysql_engine='InnoDB'
  )
  op.create_index(op.f('ix_entry_type_name'), 'entry_type', ['name'], unique=True)
  op.create_index(op.f('ix_entry_type_id'), 'entry_type', ['id'], unique=False)
  op.drop_index(op.f('ix_entries_id'), table_name='entries')
  op.drop_index(op.f('ix_entries_entry_type_id'), table_name='entries')
  op.drop_index(op.f('ix_entries_entry_date'), table_name='entries')
  op.drop_table('entries')
  op.drop_index(op.f('ix_entry_types_name'), table_name='entry_types')
  op.drop_index(op.f('ix_entry_types_id'), table_name='entry_types')
  op.drop_table('entry_types')
  # ### end Alembic commands ###
