"""Corrigir_campos_data

Revision ID: 36f088525425
Revises: 2fbe68ce301b
Create Date: 2025-09-21 10:55:32.814697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36f088525425'
down_revision: Union[str, Sequence[str], None] = '2fbe68ce301b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'entry_date',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('users', 'birthdate',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthdate',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('entries', 'entry_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
