"""adicionar_categoria_meta

Revision ID: 3ce003650cb3
Revises: 36f088525425
Create Date: 2025-10-14 21:46:01.109862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ce003650cb3'
down_revision: Union[str, Sequence[str], None] = '36f088525425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('categories',
  sa.Column('id', sa.Integer(), nullable=False),
  sa.Column('name', sa.String(length=50), nullable=False),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
  op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
  op.create_table('goals',
  sa.Column('id', sa.Integer(), nullable=False),
  sa.Column('month', sa.SmallInteger(), nullable=False),
  sa.Column('year', mysql.YEAR(), nullable=False),
  sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('category_id', sa.Integer(), nullable=True),
  sa.CheckConstraint('month BETWEEN 1 AND 12', name='check_valid_month'),
  sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_index('idx_payments_year_month', 'goals', ['year', 'month'], unique=False)
  op.create_index(op.f('ix_goals_category_id'), 'goals', ['category_id'], unique=False)
  op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
  op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
  op.add_column('entries', sa.Column('category_id', sa.Integer(), nullable=False))
  op.add_column('entries', sa.Column('user_id', sa.Integer(), nullable=False))
  op.create_index(op.f('ix_entries_category_id'), 'entries', ['category_id'], unique=False)
  op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
  op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'])
  op.create_foreign_key(None, 'entries', 'categories', ['category_id'], ['id'])
  op.execute(sa.text("INSERT INTO categories (id, name) " \
  "VALUES (1, 'Alimentação'), (2, 'Transporte'), (3, 'Entretenimento'), " \
  "(4, 'Saúde'), (5, 'Educação'), (6, 'Casa'), (7, 'Roupas'), (8, 'Outros');"))

  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, 'entries', type_='foreignkey')
  op.drop_constraint(None, 'entries', type_='foreignkey')
  op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
  op.drop_index(op.f('ix_entries_category_id'), table_name='entries')
  op.drop_column('entries', 'user_id')
  op.drop_column('entries', 'category_id')
  op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
  op.drop_index(op.f('ix_goals_id'), table_name='goals')
  op.drop_index(op.f('ix_goals_category_id'), table_name='goals')
  op.drop_index('idx_payments_year_month', table_name='goals')
  op.drop_table('goals')
  op.drop_index(op.f('ix_categories_name'), table_name='categories')
  op.drop_index(op.f('ix_categories_id'), table_name='categories')
  op.drop_table('categories')
  # ### end Alembic commands ###
