"""tabela de entry types

Revision ID: 43afb92b02bb
Revises: 7855bbbd1e98
Create Date: 2025-09-20 22:14:21.825084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43afb92b02bb'
down_revision: Union[str, Sequence[str], None] = '7855bbbd1e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_type_id'), 'entry_type', ['id'], unique=False)
    op.create_index(op.f('ix_entry_type_name'), 'entry_type', ['name'], unique=True)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('birthdate', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('profession', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###
    op.execute(sa.text("INSERT INTO entry_type (id, name) VALUES (1, 'Receita'), (2, 'Despesa');"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'city')
    op.drop_column('users', 'address')
    op.drop_column('users', 'profession')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_entry_type_name'), table_name='entry_type')
    op.drop_index(op.f('ix_entry_type_id'), table_name='entry_type')
    op.drop_table('entry_type')
    # ### end Alembic commands ###
