"""adicionar_verificacao_em_duas_etapas

Revision ID: 9468b68a4eed
Revises: cbaf1a6f8ff8
Create Date: 2025-11-02 21:20:51.474477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9468b68a4eed'
down_revision: Union[str, Sequence[str], None] = 'cbaf1a6f8ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('verifier', sa.String(length=255), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
  )
  op.create_index(op.f('ix_user_auth_id'), 'user_auth', ['id'], unique=False)
  op.create_index(op.f('ix_user_auth_user_id'), 'user_auth', ['user_id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_user_auth_user_id'), table_name='user_auth')
  op.drop_index(op.f('ix_user_auth_id'), table_name='user_auth')
  op.drop_table('user_auth')
  # ### end Alembic commands ###
