"""Adiciona relacionamento de usuario em entries

Revision ID: 9b5853c84df0
Revises: 36f088525425
Create Date: 2025-10-07 23:49:45.142623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5853c84df0'
down_revision: Union[str, Sequence[str], None] = '36f088525425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_column('entries', 'user_id')
    # ### end Alembic commands ###
