"""correcao_no_limite_imagem_usuario

Revision ID: b121e147d2e6
Revises: c7119a8bbce0
Create Date: 2025-10-25 23:42:36.747384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b121e147d2e6'
down_revision: Union[str, Sequence[str], None] = 'c7119a8bbce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=sa.BLOB(),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
