"""adicionar_imagem_usuario

Revision ID: c7119a8bbce0
Revises: 885f5c49dcf1
Create Date: 2025-10-25 23:32:53.633661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7119a8bbce0'
down_revision: Union[str, Sequence[str], None] = '885f5c49dcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('profile_image_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_image_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_type')
    op.drop_column('users', 'profile_image_name')
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
