"""adicionar_campos_recuperar_senha

Revision ID: fe5def237a8c
Revises: 00128058d6c2
Create Date: 2025-10-25 22:16:58.417393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5def237a8c'
down_revision: Union[str, Sequence[str], None] = '00128058d6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_token_expiration', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_token_expiration')
    op.drop_column('users', 'password_reset_token')
    # ### end Alembic commands ###
